# This playbook is trying to change root fanout switch port vlans when deploy leaf fanout or connect server to SONiC DUT
# This playbook is called from fanout_connect.yml or fanout.yml

- set_fact: deploy_leaf=false
  when: deploy_leaf is not defined

- set_fact: dut="{{ leaf_name }}"
  when: deploy_leaf

- set_fact:
    clean_before_add: "{{ clean_before_add | default('y') }}"

- debug: msg="Configuring fanout switch for {{ dut }}"

- name: Gathering connection facts about the DUTs or leaffanout device
  conn_graph_facts:
    host: "{{ dut if ',' not in dut else omit }}"
    hosts: "{{ dut.split(',') if ',' in dut else omit }}"
  delegate_to: localhost
  tags: always
  register: devinfo

- name: Gathering connection facts about the lab
  conn_graph_facts:
    anchor: "{{ dut.split(',') | list }}"
  delegate_to: localhost
  tags: always
  register: lab

- set_fact:
    lab_devices: "{{ lab.ansible_facts.device_info }}"

- name: Collect DUTs vlans
  set_fact:
    dev_vlans: "{{ dev_vlans|default([]) + item.value }}"
  loop: "{{ devinfo['ansible_facts']['device_vlan_range'] | default ({}) | dict2items }}"

- set_fact:
    root_dut: "{{ dut }}"

- set_fact:
    root_dev: "{{ (lab.ansible_facts.device_conn[root_dut] | dict2items | first).value.peerdevice }}"

- set_fact:
    root_hwsku: "{{ lab_devices[root_dev]['HwSku'] }}"

- set_fact:
    root_conn: "{{ lab.ansible_facts['device_conn'][root_dev] }}"

- name: Propagate root_dev fact to delegate host
  set_fact:
    root_dev: "{{ root_dev }}"
  delegate_to: "{{ root_dev }}"
  delegate_facts: true

# Deploy SONiC config to root fanout
- name: Deploy SONiC config to root fanout
  block:
    - name: Include SONiC fanout deploy tasks
      include_tasks: fanout_sonic.yml
      vars:
        inventory_hostname: "{{ root_dev }}"
  delegate_to: "{{ root_dev }}"
