- conf-name: caspian_testbed_t0_spine6
  group-name: sp6-t0
  topo: t0
  ptf_image_name: docker-ptf
  ptf: ptf_sp6-t0
  ptf_ip: 10.9.109.23/22
  ptf_ipv6: 2001:db8:109::23/64
  server: server_1
  vm_base: VM0101
  dut:
    - upscalelab2-spine6
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Vega8 6540 100G fanout links

- conf-name: caspian_testbed_t1_spine6
  group-name: sp6-t1
  topo: t1
  ptf_image_name: docker-ptf
  ptf: ptf_sp6-t1
  ptf_ip: 10.9.109.24/22
  ptf_ipv6: 2001:db8:109::24/64
  server: server_1
  vm_base: VM0101
  dut:
    - upscalelab2-spine6
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Vega8 6540 100G fanout links

- conf-name: caspian_testbed_t1-lag_spine6
  group-name: sp6t1lag
  topo: t1-lag
  ptf_image_name: docker-ptf
  ptf: ptf_sp6t1lag
  ptf_ip: 10.9.109.25/22
  ptf_ipv6: 2001:db8:109::25/64
  server: server_1
  vm_base: VM0101
  dut:
    - upscalelab2-spine6
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Vega8 6540 100G fanout links

- conf-name: caspian_testbed_t0_spine6-800
  group-name: sp6-t0
  topo: t0
  ptf_image_name: docker-ptf
  ptf: ptf_sp6-t0
  ptf_ip: 10.9.109.23/22
  ptf_ipv6: 2001:db8:109::23/64
  server: server_1
  vm_base: VM0101
  dut:
    - upscalelab2-spine6-800
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Vega8 6540 64x800G

- conf-name: caspian_testbed_t1_spine6-800
  group-name: sp6-t1
  topo: t1
  ptf_image_name: docker-ptf
  ptf: ptf_sp6-t1
  ptf_ip: 10.9.109.24/22
  ptf_ipv6: 2001:db8:109::24/64
  server: server_1
  vm_base: VM0101
  dut:
    - upscalelab2-spine6-800
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Vega8 6540 64x800G

- conf-name: caspian_testbed_t1-lag_spine6-800
  group-name: sp6t1lag
  topo: t1-lag
  ptf_image_name: docker-ptf
  ptf: ptf_sp6t1lag
  ptf_ip: 10.9.109.25/22
  ptf_ipv6: 2001:db8:109::25/64
  server: server_1
  vm_base: VM0101
  dut:
    - upscalelab2-spine6-800
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Vega8 6540 64x800G

- conf-name: caspian_testbed_t0-64_spine6-400
  group-name: sp6-t0
  topo: t0-64
  ptf_image_name: docker-ptf
  ptf: ptf_sp6-t0
  ptf_ip: 10.9.109.23/22
  ptf_ipv6: 2001:db8:109::23/64
  server: server_1
  vm_base: VM0101
  dut:
    - upscalelab2-spine6-400
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Vega8 6540 400G fanout links

- conf-name: caspian_testbed_t1-64_spine6-400
  group-name: sp6-t1
  topo: t1-64
  ptf_image_name: docker-ptf
  ptf: ptf_sp6-t1
  ptf_ip: 10.9.109.24/22
  ptf_ipv6: 2001:db8:109::24/64
  server: server_1
  vm_base: VM0101
  dut:
    - upscalelab2-spine6-400
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Vega8 6540 400G fanout links

- conf-name: caspian_testbed_t1-64-lag_spine6-400
  group-name: sp6t1lag
  topo: t1-64-lag
  ptf_image_name: docker-ptf
  ptf: ptf_sp6t1lag
  ptf_ip: 10.9.109.25/22
  ptf_ipv6: 2001:db8:109::25/64
  server: server_1
  vm_base: VM0101
  dut:
    - upscalelab2-spine6-400
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Vega8 6540 400G fanout links

- conf-name: caspian_testbed_t0_spine7
  group-name: sp7-t0
  topo: t0
  ptf_image_name: docker-ptf
  ptf: ptf_sp7-t0
  ptf_ip: 192.168.222.23/24
  ptf_ipv6: 2001:db8:122::23/64
  server: server_2
  vm_base: VM0201
  dut:
    - upscalelab2-spine7
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t1_spine7
  group-name: sp7-t1
  topo: t1
  ptf_image_name: docker-ptf
  ptf: ptf_sp7-t1
  ptf_ip: 192.168.222.24/24
  ptf_ipv6: 2001:db8:122::24/64
  server: server_2
  vm_base: VM0201
  dut:
    - upscalelab2-spine7
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t1-lag_spine7
  group-name: sp7t1lag
  topo: t1-lag
  ptf_image_name: docker-ptf
  ptf: ptf_sp7t1lag
  ptf_ip: 192.168.222.25/24
  ptf_ipv6: 2001:db8:122::25/64
  server: server_2
  vm_base: VM0201
  dut:
    - upscalelab2-spine7
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t0_spine7-800
  group-name: sp7-t0
  topo: t0
  ptf_image_name: docker-ptf
  ptf: ptf_sp7-t0
  ptf_ip: 192.168.222.23/24
  ptf_ipv6: 2001:db8:122::23/64
  server: server_2
  vm_base: VM0201
  dut:
    - upscalelab2-spine7-800
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t1_spine7-800
  group-name: sp7-t1
  topo: t1
  ptf_image_name: docker-ptf
  ptf: ptf_sp7-t1
  ptf_ip: 192.168.222.24/24
  ptf_ipv6: 2001:db8:122::24/64
  server: server_2
  vm_base: VM0201
  dut:
    - upscalelab2-spine7-800
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t1-lag_spine7-800
  group-name: sp7t1lag
  topo: t1-lag
  ptf_image_name: docker-ptf
  ptf: ptf_sp7t1lag
  ptf_ip: 192.168.222.25/24
  ptf_ipv6: 2001:db8:122::25/64
  server: server_2
  vm_base: VM0201
  dut:
    - upscalelab2-spine7-800
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t0-64_spine7-400
  group-name: sp7-t0
  topo: t0-64
  ptf_image_name: docker-ptf
  ptf: ptf_sp7-t0
  ptf_ip: 192.168.222.23/24
  ptf_ipv6: 2001:db8:122::23/64
  server: server_2
  vm_base: VM0201
  dut:
    - upscalelab2-spine7-400
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox 2x400G 64-port

- conf-name: caspian_testbed_t1-64_spine7-400
  group-name: sp7-t1
  topo: t1-64
  ptf_image_name: docker-ptf
  ptf: ptf_sp7-t1
  ptf_ip: 192.168.222.24/24
  ptf_ipv6: 2001:db8:122::24/64
  server: server_2
  vm_base: VM0201
  dut:
    - upscalelab2-spine7-400
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox 2x400G 64-port

- conf-name: caspian_testbed_t1-64-lag_spine7-400
  group-name: sp7t1lag
  topo: t1-64-lag
  ptf_image_name: docker-ptf
  ptf: ptf_sp7t1lag
  ptf_ip: 192.168.222.25/24
  ptf_ipv6: 2001:db8:122::25/64
  server: server_2
  vm_base: VM0201
  dut:
    - upscalelab2-spine7-400
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox 2x400G 64-port

- conf-name: caspian_testbed_t0_spine8
  group-name: sp8-t0
  topo: t0
  ptf_image_name: docker-ptf
  ptf: ptf_sp8-t0
  ptf_ip: 192.168.223.23/24
  ptf_ipv6: 2001:db8:123::23/64
  server: server_3
  vm_base: VM0301
  dut:
    - upscalelab2-spine8
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t1_spine8
  group-name: sp8-t1
  topo: t1
  ptf_image_name: docker-ptf
  ptf: ptf_sp8-t1
  ptf_ip: 192.168.223.24/24
  ptf_ipv6: 2001:db8:123::24/64
  server: server_3
  vm_base: VM0301
  dut:
    - upscalelab2-spine8
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t1-lag_spine8
  group-name: sp8t1lag
  topo: t1-lag
  ptf_image_name: docker-ptf
  ptf: ptf_sp8t1lag
  ptf_ip: 192.168.223.25/24
  ptf_ipv6: 2001:db8:123::25/64
  server: server_3
  vm_base: VM0301
  dut:
    - upscalelab2-spine8
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t0_spine8-800
  group-name: sp8-t0
  topo: t0
  ptf_image_name: docker-ptf
  ptf: ptf_sp8-t0
  ptf_ip: 192.168.223.23/24
  ptf_ipv6: 2001:db8:123::23/64
  server: server_3
  vm_base: VM0301
  dut:
    - upscalelab2-spine8-800
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t1_spine8-800
  group-name: sp8-t1
  topo: t1
  ptf_image_name: docker-ptf
  ptf: ptf_sp8-t1
  ptf_ip: 192.168.223.24/24
  ptf_ipv6: 2001:db8:123::24/64
  server: server_3
  vm_base: VM0301
  dut:
    - upscalelab2-spine8-800
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t1-lag_spine8-800
  group-name: sp8t1lag
  topo: t1-lag
  ptf_image_name: docker-ptf
  ptf: ptf_sp8t1lag
  ptf_ip: 192.168.223.25/24
  ptf_ipv6: 2001:db8:123::25/64
  server: server_3
  vm_base: VM0301
  dut:
    - upscalelab2-spine8-800
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t0-64_spine8-800
  group-name: sp8-t064
  topo: t0-64
  ptf_image_name: docker-ptf
  ptf: ptf_sp8-t064
  ptf_ip: 192.168.223.26/24
  ptf_ipv6: 2001:db8:123::26/64
  server: server_3
  vm_base: VM0301
  dut:
    - upscalelab2-spine8-800
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox 64-port

- conf-name: caspian_testbed_t1-64_spine8-800
  group-name: sp8-t164
  topo: t1-64
  ptf_image_name: docker-ptf
  ptf: ptf_sp8-t164
  ptf_ip: 192.168.223.27/24
  ptf_ipv6: 2001:db8:123::27/64
  server: server_3
  vm_base: VM0301
  dut:
    - upscalelab2-spine8-800
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox 64-port

- conf-name: caspian_testbed_t0_spine9
  group-name: sp9-t0
  topo: t0
  ptf_image_name: docker-ptf
  ptf: ptf_sp9-t0
  ptf_ip: 192.168.211.23/24
  ptf_ipv6: 2001:db8:124::23/64
  server: server_4
  vm_base: VM0401
  dut:
    - upscalelab2-spine9
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t1_spine9
  group-name: sp9-t1
  topo: t1
  ptf_image_name: docker-ptf
  ptf: ptf_sp9-t1
  ptf_ip: 192.168.211.24/24
  ptf_ipv6: 2001:db8:124::24/64
  server: server_4
  vm_base: VM0401
  dut:
    - upscalelab2-spine9
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t1-lag_spine9
  group-name: sp9t1lag
  topo: t1-lag
  ptf_image_name: docker-ptf
  ptf: ptf_sp9t1lag
  ptf_ip: 192.168.211.25/24
  ptf_ipv6: 2001:db8:124::25/64
  server: server_4
  vm_base: VM0401
  dut:
    - upscalelab2-spine9
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t0_spine9-800
  group-name: sp9-t0
  topo: t0
  ptf_image_name: docker-ptf
  ptf: ptf_sp9-t0
  ptf_ip: 192.168.211.23/24
  ptf_ipv6: 2001:db8:124::23/64
  server: server_4
  vm_base: VM0401
  dut:
    - upscalelab2-spine9-800
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox


- conf-name: caspian_testbed_t1_spine9-800
  group-name: sp9-t1
  topo: t1
  ptf_image_name: docker-ptf
  ptf: ptf_sp9-t1
  ptf_ip: 192.168.211.24/24
  ptf_ipv6: 2001:db8:124::24/64
  server: server_4
  vm_base: VM0401
  dut:
    - upscalelab2-spine9-800
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t1-lag_spine9-800
  group-name: sp9t1lag
  topo: t1-lag
  ptf_image_name: docker-ptf
  ptf: ptf_sp9t1lag
  ptf_ip: 192.168.211.25/24
  ptf_ipv6: 2001:db8:124::25/64
  server: server_4
  vm_base: VM0401
  dut:
    - upscalelab2-spine9-800
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t0-64_spine9-400
  group-name: sp9-t0
  topo: t0-64
  ptf_image_name: docker-ptf
  ptf: ptf_sp9-t0
  ptf_ip: 192.168.211.23/24
  ptf_ipv6: 2001:db8:124::23/64
  server: server_4
  vm_base: VM0401
  dut:
    - upscalelab2-spine9-400
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox 2x400G 64-port

- conf-name: caspian_testbed_t1-64_spine9-400
  group-name: sp9-t1
  topo: t1-64
  ptf_image_name: docker-ptf
  ptf: ptf_sp9-t1
  ptf_ip: 192.168.211.24/24
  ptf_ipv6: 2001:db8:124::24/64
  server: server_4
  vm_base: VM0401
  dut:
    - upscalelab2-spine9-400
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox 2x400G 64-port

- conf-name: caspian_testbed_t1-64-lag_spine9-400
  group-name: sp9t1lag
  topo: t1-64-lag
  ptf_image_name: docker-ptf
  ptf: ptf_sp9t1lag
  ptf_ip: 192.168.211.25/24
  ptf_ipv6: 2001:db8:124::25/64
  server: server_4
  vm_base: VM0401
  dut:
    - upscalelab2-spine9-400
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox 2x400G 64-port

- conf-name: caspian_testbed_t0_spine10
  group-name: sp10-t0
  topo: t0
  ptf_image_name: docker-ptf
  ptf: ptf_sp10-t0
  ptf_ip: 10.9.107.165/16
  ptf_ipv6: 2001:db8:107::165/64
  server: server_5
  vm_base: VM0501
  dut:
    - spine10
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t1_spine10
  group-name: sp10-t1
  topo: t1
  ptf_image_name: docker-ptf
  ptf: ptf_sp10-t1
  ptf_ip: 10.9.107.166/16
  ptf_ipv6: 2001:db8:107::166/64
  server: server_5
  vm_base: VM0501
  dut:
    - spine10
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t1-lag_spine10
  group-name: 10t1lag
  topo: t1-lag
  ptf_image_name: docker-ptf
  ptf: ptf_s10t1lag
  ptf_ip: 10.9.107.167/16
  ptf_ipv6: 2001:db8:107::167/64
  server: server_5
  vm_base: VM0501
  dut:
    - spine10
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t0_spine10-800
  group-name: sp10-t0
  topo: t0
  ptf_image_name: docker-ptf
  ptf: ptf_sp10-t0
  ptf_ip: 10.9.107.165/16
  ptf_ipv6: 2001:db8:107::165/64
  server: server_5
  vm_base: VM0501
  dut:
    - spine10-800
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t1_spine10-800
  group-name: sp10-t1
  topo: t1
  ptf_image_name: docker-ptf
  ptf: ptf_sp10-t1
  ptf_ip: 10.9.107.166/16
  ptf_ipv6: 2001:db8:107::166/64
  server: server_5
  vm_base: VM0501
  dut:
    - spine10-800
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_t1-lag_spine10-800
  group-name: 10t1lag
  topo: t1-lag
  ptf_image_name: docker-ptf
  ptf: ptf_s10t1lag
  ptf_ip: 10.9.107.167/16
  ptf_ipv6: 2001:db8:107::167/64
  server: server_5
  vm_base: VM0501
  dut:
    - spine10-800
  inv_name: veos
  auto_recover: 'False'
  comment: Test ptf Mellanox

- conf-name: caspian_testbed_snappi_sonic
  group-name: vms6-1
  topo: snappi-sonic
  ptf_image_name: docker-ptf-snappi
  ptf: snappi-sonic-ptf
  ptf_ip: 10.9.108.101
  ptf_ipv6:
  server: server_10
  vm_base:
  dut:
    - upscale-sys-spine1
    - upscale-sys-leaf1
  inv_name: snappi-sonic
  auto_recover: 'False'
  comment: Test snappi Mellanox

