name: Semgrep

on:
  pull_request: {}
  push:
    branches:
      - upscaleai-202505-5610

jobs:
  semgrep:
    if: github.repository_owner == 'sonic-net'
    name: Semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
        env:
           SEMGREP_RULES: p/default
